// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// metaCluster
int metaCluster(std::string file, double eps, int minPts, std::string outputFile, std::string saveStatusOutputFile, std::string loadFromFile);
RcppExport SEXP _DPDensityBased_metaCluster(SEXP fileSEXP, SEXP epsSEXP, SEXP minPtsSEXP, SEXP outputFileSEXP, SEXP saveStatusOutputFileSEXP, SEXP loadFromFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type minPts(minPtsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputFile(outputFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type saveStatusOutputFile(saveStatusOutputFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type loadFromFile(loadFromFileSEXP);
    rcpp_result_gen = Rcpp::wrap(metaCluster(file, eps, minPts, outputFile, saveStatusOutputFile, loadFromFile));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DPDensityBased_metaCluster", (DL_FUNC) &_DPDensityBased_metaCluster, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DPDensityBased(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
