---
title: "DP visual output"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)

path = "C:\\Users\\UserX\\CLionProjects\\DP\\Data\\Sources\\"
file = "t4.8k.dat"
outputFile = "C:\\Users\\UserX\\CLionProjects\\DP\\Data\\Results\\t4.8k.dat"
eps = 10
minPts = 25

inp <- file("C:\\Users\\Peter\\CLionProjects\\DP\\Data\\Sources\\t4.8k.dat","r")
inp_first_line <- readLines(inp,n=1)
close(inp)
dim <- lengths(as.list(strsplit(inp_first_line, " ")))

result1Name = paste(substr(outputFile, 0,nchar(outputFile)-4), "_clustering_output_", minPts, "_", eps, ".txt", sep = "");
result2Name = paste(substr(outputFile, 0,nchar(outputFile)-4), "_clustering_output_cells_", minPts, "_", eps, ".txt", sep = "")

DPDensityBased::metaCluster(paste(path, file, sep = ""), eps, minPts)

result1 <- read.table(result1Name, header = F)
result2 <- read.table(result2Name, header = F)


my_theme <- theme(axis.text=element_text(size=12),
                  axis.title=element_text(size=13,face="bold"),
                  panel.background = element_rect(color = "grey25", fill = "white"),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank())

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
v = vector()
for(i in 1:dim) {
   v[i] <- i
}

selectInput("x", "Y Axis Dim", v, selected = "1")
selectInput("y", "X Axis Dim", v, selected = "2")
selectInput("show", "Show", c("Points", "Cells"), selected = "Points")
```

Column
-----------------------------------------------------------------------
### Graph viz

```{r}
renderPlot({
if((input$show) == "Points")
  result <- result1
else
  result <- result2
  
x_c <- names(result)[as.numeric(input$x)]
y_c <- names(result)[as.numeric(input$y)]
ggplot(data.frame(result[,c(as.numeric(input$x), as.numeric(input$y))], Class = as.character(result[,dim+1])),
aes(result[,as.numeric(input$x)], result[,as.numeric(input$y)])) +
geom_point(aes(colour = Class, shape = ), size = 3, alpha = 1) +
my_theme +
labs(title = file) +
labs(x = x_c, y = y_c)
})

```
