# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metaCluster <- function(file = "C:\\Users\\Peter\\CLionProjects\\DP\\Data\\Sources\\t4.8k.dat", eps = 10, minPts = 25L, outputFile = "C:\\Users\\Peter\\CLionProjects\\DP\\Data\\Results\\t4.8k_abc123.dat", saveStatusOutputFile = "", loadFromFile = "") {
    .Call(`_DPDensityBased_metaCluster`, file, eps, minPts, outputFile, saveStatusOutputFile, loadFromFile)
}

